android_binary(
  name = 'game',
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  deps = [
    '//java/net/marcv81/gfx2d:gfx2d',
    '//java/net/marcv81/game:game',
    '//app:res',
  ],
)

android_resource(
  name = 'res',
  res = 'res',
  manifest = 'AndroidManifest.xml',
  visibility = [
    '//app:game',
  ],
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)

project_config(
  src_target = ':game',
)
