android_resource(
  name = 'res',
  res = 'res',
  package = 'net.marcv81.spacedroid.game',
  visibility = [
    '//java/net/marcv81/spacedroid/game:lib',
  ],
)

project_config(
  src_target = '//res/net/marcv81/spacedroid/game:res',
)
