android_binary(
  name = 'bin',
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  deps = [
    '//java/net/marcv81/spacedroid:lib',
    '//spacedroid:res',
  ],
)

android_resource(
  name = 'res',
  res = 'res',
  manifest = 'AndroidManifest.xml',
  visibility = [
    '//spacedroid:bin',
  ],
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)

project_config(
  src_target = '//spacedroid:bin',
)
