android_resource(
  name = 'res',
  res = 'res',
  package = 'net.marcv81.game',
  visibility = [
    '//java/net/marcv81/game:game',
  ],
)

project_config(
  src_target = ':res',
  src_roots = None,
)

